### ISSUE TITLE
Script is detected as malware by some AV vendors and deleted

### ISSUE THREAD

**Issue by siddharth3586** [BornToBeRoot/PowerShell_IPv4NetworkScanner#10]
As soon as the script is saved in notepad++ using power shell extension, It gets disappeared/

**Comment by BornToBeRoot** [comment]
Hi @siddharth3586 

I can not reproduce the problem on my end. But I suspect that your antivirus deletes the file. Apparently some vendors consider my script as malware (or whatever) (for whatever reason.).

![image](https://github.com/BornToBeRoot/PowerShell_IPv4NetworkScanner/assets/16019165/67767d28-495c-4d14-b15b-87dcbaea9ccd)

https://www.virustotal.com/gui/file/6e28b4039ca4c9f110ef755a5eaf20ee2de0d9e9532d38903a637919c2555073/detection

Maybe you can download it and whitelist it on your local computer.

Anyone can review the script on GitHub and check for themselves if it is malicious or not and if they want to use it. #OpenSource

**Comment by siddharth3586** [comment]
Sure. Thanks for the information.  Is there a way for me to do a network scan (passively) and get a list of all the ports, IP addresses, devices, software installed, batch jobs? 

Can you provide me some guidance on the approach

**Comment by BornToBeRoot** [comment]
For PowerShell, you can do something simple (but slow) like this:
Ping: 
`0..255 | % {Test-NetConnection -ComputerName "192.168.0.$_"}`
Open Port (e.g. 22)
`0..255 | % {Test-NetConnection -ComputerName "192.168.0.$_" -Port 22}`

---

If you want something with a UI and more features (like IP Scanner, Traceroute, Ping Monitor, etc.) you can try my [NETworkManager](https://github.com/BornToBeRoot/NETworkManager/):

![image](https://github.com/BornToBeRoot/PowerShell_IPv4NetworkScanner/assets/16019165/90203968-40f5-4a4e-bd6a-a68f10aaf288)

Latest release: https://github.com/BornToBeRoot/NETworkManager/releases/

Edit: Here is an overview of all features & some docs: https://borntoberoot.net/NETworkManager/Features
