### ISSUE TITLE
EnableMACResolving

### ISSUE THREAD

**Issue by michaldejmek** [BornToBeRoot/PowerShell_IPv4NetworkScanner#11]
When using the "-EnableMACResolving" function, the above information was not detected. The IP and hostname were detected correctly, but nothing more.

**Comment by BornToBeRoot** [comment]
@michaldejmek Is your client in the same subnet? ARP requires Layer 2

**Comment by michaldejmek** [comment]
@BornToBeRoot  It's a remote network - Locally, everything works as it should.
