### ISSUE TITLE
truncated IP results

### ISSUE THREAD

**Issue by thibautsergent** [BornToBeRoot/PowerShell_IPv4NetworkScanner#4]
When I run the script, some IP are truncated like that : " 172.16.100... "

IP should be shown as 172.16.100.100

This occurs when I scan this range : _172.16.20.1 - 172.16.254.0_ OR _172.16.99.1 - 172.16.101.1_
But didn't occurs with this range : _172.16.99.99_ - _172.16.101.1_

**Comment by thibautsergent** [comment]
This workaround solved the problem : 

At the end of line 653, add  -AutoSize

**Comment by BornToBeRoot** [comment]
The script returns a pscustomobject. You can pipe it into a `format-list` or `format-table` to change the format (or use a foreach --> `| % { Write-Host "IP: $($_.IPv4Address)"}` .

Example:
`.\IPv4NetworkScan.ps1 -IPv4Address 192.168.178.0 -CIDR 25 | Format-Table`
