### ISSUE TITLE
Can this scan ports too?

### ISSUE THREAD

**Issue by ghost** [BornToBeRoot/PowerShell_IPv4NetworkScanner#5]
Can you add the ability to scan multiple ports?  Then this would be an all around best tool to use.  thanks.

**Comment by BornToBeRoot** [comment]
You can use this script and combine it with the port scanner https://github.com/BornToBeRoot/PowerShell_IPv4PortScanner

You can use the result from this script and do a foreach for a port scan 😄

**Comment by BornToBeRoot** [comment]
If you look for a tool with a UI you can try this: https://github.com/BornToBeRoot/NETworkManager

The port scanner allows multiple hosts, ip ranges, etc..
