### ISSUE TITLE
vendor mac list site down

### ISSUE THREAD

**Issue by itschuckster** [BornToBeRoot/PowerShell_IPv4NetworkScanner#6]
oui.txt is not being generated as the site is down. Here is a replacement I found on the web, however, it would require and update to your parser. 

https://gist.githubusercontent.com/aallan/b4bb86db86079509e6159810ae9bd3e4/raw/846ae1b646ab0f4d646af9115e47365f4118e5f6/mac-vendor.txt

**Comment by BornToBeRoot** [comment]
Hi,
thanks for reporting. The question is whether the site is temporarily down or permanently -.-

I think the alternative would be the offical list from here: https://standards-oui.ieee.org/oui/oui.txt

Greetings

**Comment by BornToBeRoot** [comment]
@itschuckster fixed in the latest version!
