### ISSUE TITLE
Wrong MAC address (thus wrong Vendor) in results

### ISSUE THREAD

**Issue by braggpeaks** [BornToBeRoot/PowerShell_IPv4NetworkScanner#8]
MAC addresses and Vendors are incorrectly assigned if IPs start with same substring (e.g. 192.168.0.1 and 192.168.0.101).
Replace line 494 with
`if($Line.TrimStart().StartsWith($IPv4Address.IPAddressToString + " "))`
and $MAC of 192.168.0.1 will not get assigned again by 192.168.0.101.

Or use Get-NetNeighbor cmdlet to resolve MAC from IP (presumably slower for this implementation).

**Comment by BornToBeRoot** [comment]
@braggpeaks thanks!

It should be fixed now.
