### ISSUE TITLE
Create-OUIListFromWeb.ps1 optimization

### ISSUE THREAD

**Issue by scriptingstudio** [BornToBeRoot/PowerShell_IPv4NetworkScanner#9]
The current implementation is too slow and academic.
I would suggest to directly save as CSV. It looks more powershellish.
```powershell
# "base" or "hex" can be chosen for filtering
# ";" or "," can be chosen as CSV delimiter
$progressPreference = 'silentlyContinue'
$LatestOUIs = (Invoke-WebRequest -Uri "https://standards-oui.ieee.org/oui/oui.txt" -UseBasicParsing).Content -split '[\r\n]' | 
Select-String '\(base 16\)' | 
. { process {$_ -replace '\s+\(base 16\)\s+',','}}
$progressPreference = 'Continue'

@('OUI,Name') + $LatestOUIs | Out-File -FilePath "$PSScriptRoot\Resources\oui.csv" -Encoding utf8
```

Yet there is a problem with duplicate ouis. The scanner selects the first entry which is likely incorrect.
CSV will eliminate dup issues.

### UPDATE
duplicates
it is likely the same company with different names
```powershell
Count Name   Group
----- ----   -----
    3 080030 {@{uoi=080030; name=NETWORK RESEARCH CORPORATION}, @{uoi=080030; name=ROYAL MELBOURNE INST OF TECH}, @{uoi=080030; name=CERN}}
    2 0001C8 {@{uoi=0001C8; name=THOMAS CONRAD CORP.}, @{uoi=0001C8; name=CONRAD CORP.}}
```

2nd
in PS7 `Invoke-WebRequest` is slow

**Comment by BornToBeRoot** [comment]
You can send me a pull request with the changes if you want. The lines below also need to be updated then.
This might be a bit faster, but how often do you generate/update the list?

I am not sure how to solve the problem with the duplicates. I currently use a set with key `MAC` value `Vendor` so i can directly access the key. If i use something like a list with for/foreach to match multiple vendors, this will get slow...
https://github.com/BornToBeRoot/PowerShell_IPv4NetworkScanner/blob/ee650b311f907d7db039fab5772d951423776553/Scripts/IPv4NetworkScan.ps1#L381-L393

**Comment by scriptingstudio** [comment]
A bit faster? 
`+=` operator with strings in cycle of 100K lines takes a desparately HUGE amount of time. 
Even this small optimization will speed up the script:
```powershell
$Output = foreach($Line in $LatestOUIs -split '[\r\n]') {
    if($Line -match "base 16")
    {        
        # Line looks like: 2405F5     (base 16)		Integrated Device Technology (Malaysia) Sdn. Bhd.
        ($Line -replace '\s+', ' ').Replace(' (base 16) ', '|').Trim()
    }
}
$Output | Out-File -FilePath "$PSScriptRoot\Resources\oui.txt"
```

Also, in the scanner script `try/catch` with string evaluation in cycle of 30K lines is desparately slow.
